### ISSUE TITLE
Bug: Transaction failed toast without error message with big slippage

### ISSUE THREAD

**Issue by Tbaut** [galacticcouncil/Basilisk-ui-old#200] opened 2022-04-13 21:55 UTC
### Description

Situation best described in a screencast

https://user-images.githubusercontent.com/33178835/163276514-3afae403-956c-4994-b7e8-027ba9c83939.mp4

### Expected Behavior

Tell me what's wrong and not allow to do the transaction
### Actual Behavior

When clicking on the swap button, I get a "transaction failed" toast, without being prompted for signing

### Steps to Reproduce

It doesn't happen often but I had the issue a couple times in several minutes
1. select a high slippage
2. select high amounts to swap
3. I clicked around like on the double arrow to exchange the get/pay but not sure if that messed up some state

The console error in the dev tool is the following
```
Uncaught (in promise) Error: createType(Call):: Call: failed decoding xyk.sell:: Struct: failed on args: {"asset_in":"u32","asset_out":"u32","amount":"u128","max_limit":"u128","discount":"bool"}:: Struct: failed on max_limit: u128:: u128: Negative number passed to unsigned type
    Kh type.js:56
    createTypeUnsafe registry.js:289
    o createUnchecked.js:17
    n Decorate.js:382
    r sell.tsx:37
    hZ TradeForm.tsx:460
    hZ TradeForm.tsx:452
    Lc React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    d useFormState.ts:73
    next createSubject.ts:22
    V createFormControl.ts:785
    hZ TradeForm.tsx:557
    Lc React
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    D scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
```

### Your Environment

* Operating System and version:Linux mint with Firefox 99

**Comment by Cubo25** [comment] 2022-09-05 14:50
I am closing this issue as nobody encountered this again and since we are already live. @Tbaut please kindly try such a scenario once again and if the problem is reproducible re-open the issue.

Thanks

**Closed as completed by Cubo25** 2022-09-05 14:50 UTC
Labels: bug

**Comment by Tbaut** [comment] 2022-09-05 15:06
Sure, I opened those issues back then when you were saying you were incentivizing ppl to find bugs and open issues.. So I did, and those issues basically never got any attention, nor feedback, nor actually any incentive ¯\\\_(ツ)\_/¯
