### ISSUE TITLE
Bug: infinitely pending tx

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/Basilisk-ui-old#1074] opened 2022-07-20 10:30 UTC
Block production stops during a pending tx, block production restarts but tx infinitely pending
### Description

- processing a "remove liquidity" transaction
- transaction pending
- green light changes to amber and then red whilst transaction is pending (block production has stopped)
- RPC is rebooted to re-engage block production
- transaction still pending up to and including the end of time
- 
<img width="1657" alt="image" src="https://user-images.githubusercontent.com/97540577/179960693-6f8a4b49-7298-480b-ba18-cabc1818f5a8.png">

### Expected Behavior

once block production restarts, I would expect my transaction to complete or fail
### Actual Behavior

infinitely pending
### Steps to Reproduce

1.
2.
3.

### Your Environment

* Toolchain versions: 
* Version used:
* System type: 
* Operating System and version:
* System specs:

**Comment by Cubo25** [comment] 2022-07-26 13:16
@lolmcshizz Can you provide more info ? I am not able to reproduce it.
https://bsx.play.hydration.cloud/#/pools?assetIn=5&assetOut=0
Latest block: 491956
Version: f828d8b

**Comment by Cubo25** [comment] 2022-09-05 15:16
After discussion with @lolmcshizz closing this issue.

**Closed as completed by Cubo25** 2022-09-05 15:16 UTC
Labels: bug
